server:
  port: 80
#  servlet:
#    context-path: /activiti

security:
  basic:
    enabled: false

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/aceace?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
#    username: root
#    password: root


    url: jdbc:mysql://47.100.251.90:3306/aceace?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
    username: root
    password: lk9527

  thymeleaf:
    #mode: LEGACYHTML5
    mode: HTML
    cache: false
    prefix: classpath:/templates
    servlet:
      content-type: text/html


  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录

#mybatis config
mybatis:
  mapper-locations: classpath:/mapper/*.xml